; Listing generated by Microsoft (R) Optimizing Compiler Version 19.22.27905.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\sglee\AppData\Local\Temp\3\.NETFramework,Version=v4.7.2.AssemblyAttributes.cpp"
